// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQoxwZmJAd7ZieJrGWiYGQ6anYYnTBK8Q',
    appId: '1:161739963411:web:a6e57dc89b4f1bad2353e6',
    messagingSenderId: '161739963411',
    projectId: 'catalogo-de-livros-aikido',
    authDomain: 'catalogo-de-livros-aikido.firebaseapp.com',
    storageBucket: 'catalogo-de-livros-aikido.appspot.com',
    measurementId: 'G-VG2D4ED2J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcduG4___O6YDkbaGAWNmdLn1SVIq_enA',
    appId: '1:161739963411:android:aea325d5250b438c2353e6',
    messagingSenderId: '161739963411',
    projectId: 'catalogo-de-livros-aikido',
    storageBucket: 'catalogo-de-livros-aikido.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIZu3D2dNl-fiEWJAQ6Q4vbOT6AeUoc98',
    appId: '1:161739963411:ios:b45f6be5804881ec2353e6',
    messagingSenderId: '161739963411',
    projectId: 'catalogo-de-livros-aikido',
    storageBucket: 'catalogo-de-livros-aikido.appspot.com',
    iosClientId: '161739963411-q395v3hdv01kt3oitk6mqoitjag7ovqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogoLivroAikidow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIZu3D2dNl-fiEWJAQ6Q4vbOT6AeUoc98',
    appId: '1:161739963411:ios:b45f6be5804881ec2353e6',
    messagingSenderId: '161739963411',
    projectId: 'catalogo-de-livros-aikido',
    storageBucket: 'catalogo-de-livros-aikido.appspot.com',
    iosClientId: '161739963411-q395v3hdv01kt3oitk6mqoitjag7ovqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogoLivroAikidow',
  );
}
